/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-01-29 16:05:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import site_cours.dao.ServiceDAO;
import site_cours.models.Service;

public final class addService_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/includes/header.jsp", Long.valueOf(1548772869638L));
    _jspx_dependants.put("/WEB-INF/includes/menu.jsp", Long.valueOf(1548775005822L));
    _jspx_dependants.put("/WEB-INF/includes/footer.html", Long.valueOf(1548760857235L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>Site cours (AddService)</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/reset.css\">\r\n");
      out.write("\t\t<link  rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/bootstrap-4.2.1/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./assets/css/gabaritSemantique.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"./assets/boostrap-4.2.1/js/boostrap.min.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\t<body>\r\n");
      out.write("\t\t\t<div id=\"global\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t<h1>Gabarit 02</h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"sous-titre\">en-tête, corps et pied de page séparés, menu vertical à gauche, largeur fixe 960px</p>\r\n");
      out.write("\t\t\t\t</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<aside>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t");

				ServiceDAO servDao = new ServiceDAO();
				for(Service service :servDao.getAllServices()){
					out.print("<li><a href='./accueil?idCat="+service.getCodeservice()+"'>"+ service.getLibelle()+"</a></li>");
				}
			
      out.write("\r\n");
      out.write("\t\t\t<li>--------------------</li>\r\n");
      out.write("\t\t\t<li><a href=\"./accueil\">Tous les services</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"./addService\">Ajouter un service</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"./addEmploye\">Ajouter un employé</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<article id=\"contenu\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1>Ajouter une catégorie</h1>\r\n");
      out.write("\t\t<form action=\"\" name=\"\" method=\"POST\">\r\n");
      out.write("\t\t\t<p><label for=\"\">Libellé : </label></p>\r\n");
      out.write("\t\t\t<p><input type=\"text\" id=\"txtLib\" name=\"txtLib\" placeholder=\"Votre libellé\"/></p>\r\n");
      out.write("\t\t\t<p><input type=\"submit\" name=\"btnAjouter\" id=\"btnAjouter\" value=\"Ajouter\"/></p>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t\t<p>Footer</p>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t \t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
